name: changefly
description: Changefly flutter app.
author: devkabiir <dev@kabiir.com>
homepage: https://github.com/devkabiir/changefly
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
